package CPU_6502;

public enum OPCODES_ENUM {

	INS_LDA_IM, INS_LDA_ZP, INS_LDA_ZX, INS_LDA_AB, INS_LDA_AX, INS_LDA_AY, INS_LDA_IX, INS_LDA_IY,

// LDX OPCODES
	INS_LDX_IM, INS_LDX_ZP, INS_LDX_ZPY, INS_LDX_AB, INS_LDX_ABY,

	// LDY OPCODES
	INS_LDY_IM, INS_LDY_ZP, INS_LDY_ZPX, INS_LDY_AB, INS_LDY_ABX,

	// STA OPCODES
	INS_STA_ZP, INS_STA_ZPX, INS_STA_AB, INS_STA_ABX, INS_STA_ABY, INS_STA_INX, INS_STA_INY,

	// STX OPCODES
	INS_STX_ZP, INS_STX_ZPY, INS_STX_AB,

	// STX OPCODES
	INS_STY_ZP, INS_STY_ZPX, INS_STY_AB,

	// TAX OPCODE
	INS_TAX_IP,

	// TAY OPCODE
	INS_TAY_IP,

	// TXA OPCODE
	INS_TXA_IP,

	// TYA OPCODE
	INS_TYA_IP,

	INS_JSR, INS_RTS,

	INS_JMP_AB, INS_JMP_IN

}
